interface InvoiceTemplateProps {
  invoice: {
    invoiceNumber: string;
    orderNumber: string;
    date: string;
    dueDate: string;
    customer: {
      name: string;
      location: string;
      email: string;
      farmName: string;
      farmNumber: string;
      contactName: string;
      phoneNumber: string;
      pobox: string;
    };
    items: {
      name: string;
      quantity: number;
      unitPrice: number;
      totalPrice: number;
    }[];
    subtotal: number;
    vat: number;
    total: number;
    type: string;
    approvedBy: string;
    approvedDate: string;
    generatedBy?: string;
  };
}

export default function InvoicePrintTemplate({ invoice }: InvoiceTemplateProps) {
  return (
    <div className="min-h-screen bg-white">
      {/* Back Button - Only visible on screen, not in print */}
      <div className="print:hidden p-4 flex justify-between items-center border-b">
        <button 
          onClick={() => window.history.back()}
          className="flex items-center text-[#066b3a] hover:text-[#055830]"
        >
          ← Back
        </button>
        <button 
          onClick={() => window.print()}
          className="bg-[#066b3a] text-white px-4 py-2 rounded flex items-center gap-2 hover:bg-[#055830]"
        >
          Print Invoice
        </button>
      </div>

      {/* Invoice Content */}
      <div className="max-w-4xl mx-auto p-8 print:p-4">
        {/* Header */}
        <div className="flex justify-between items-start mb-12">
          <div>
            <h1 className="text-3xl font-bold text-[#066b3a] mb-2">SpaDe Company</h1>
            <div className="text-gray-600 space-y-1">
              <p>1B Tanganyika - Maichagange Street</p>
              <p>+255 (0)653461126/+255(0)754574743</p>
              <div>
                <a href="mailto:info@spade.co.tz" className="text-[#066b3a]">info@spade.co.tz</a>,{' '}
                <a href="http://www.spade.co.tz" className="text-[#066b3a]">www.spade.co.tz</a>
              </div>
            </div>
          </div>
          <div className="text-right">
            <h2 className="text-4xl font-bold text-[#066b3a] mb-2">INVOICE</h2>
            <div className="text-gray-600 space-y-1">
              <p>Invoice #: {invoice.invoiceNumber}</p>
              <p>Order #: {invoice.orderNumber}</p>
              <p>Date: {invoice.date}</p>
              <p>Due Date: {invoice.dueDate}</p>
              <p>Type: {invoice.type}</p>
            </div>
          </div>
        </div>

        {/* Customer Details */}
        <div className="grid grid-cols-2 gap-8 mb-12">
          <div>
            <h3 className="text-gray-800 font-bold text-lg mb-3">Bill To:</h3>
            <div className="text-gray-600 space-y-1">
              <p className="font-semibold text-gray-800">{invoice.customer.name}</p>
              <p>Farm: {invoice.customer.farmName}</p>
              <p>Farm No: {invoice.customer.farmNumber}</p>
              <p>{invoice.customer.location}</p>
              <p>P.O. Box {invoice.customer.pobox}</p>
              <p>Contact: {invoice.customer.contactName}</p>
              <p>Phone: {invoice.customer.phoneNumber}</p>
              {invoice.customer.email && <p>Email: {invoice.customer.email}</p>}
            </div>
          </div>
          <div className="text-right">
            <h3 className="text-gray-800 font-bold text-lg mb-3">Invoice Details:</h3>
            <div className="text-gray-600 space-y-1">
              <p>Generated By: {invoice.generatedBy}</p>
              <p>Approved By: {invoice.approvedBy}</p>
              <p>Approved Date: {invoice.approvedDate}</p>
            </div>
          </div>
        </div>

        {/* Items Table */}
        <div className="mb-12">
          <table className="w-full">
            <thead>
              <tr className="border-y-2 border-[#066b3a]">
                <th className="py-3 text-left text-gray-800 font-semibold">Description</th>
                <th className="py-3 text-center text-gray-800 font-semibold">Quantity</th>
                <th className="py-3 text-right text-gray-800 font-semibold">Unit Price (TZS)</th>
                <th className="py-3 text-right text-gray-800 font-semibold">Total (TZS)</th>
              </tr>
            </thead>
            <tbody>
              {invoice.items.map((item, index) => (
                <tr key={index} className="border-b border-gray-200">
                  <td className="py-4 text-gray-800">{item.name}</td>
                  <td className="py-4 text-center text-gray-800">{item.quantity}</td>
                  <td className="py-4 text-right text-gray-800">
                    {item.unitPrice.toLocaleString()}
                  </td>
                  <td className="py-4 text-right text-gray-800">
                    {item.totalPrice.toLocaleString()}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Totals */}
        <div className="flex justify-end mb-12">
          <div className="w-80 space-y-3">
            <div className="flex justify-between py-2 border-b border-gray-200">
              <span className="text-gray-600">Subtotal:</span>
              <span className="text-gray-800 font-semibold">
                {invoice.subtotal.toLocaleString()} TZS
              </span>
            </div>
            <div className="flex justify-between py-2 border-b border-gray-200">
              <span className="text-gray-600">VAT (18%):</span>
              <span className="text-gray-800 font-semibold">
                {invoice.vat.toLocaleString()} TZS
              </span>
            </div>
            <div className="flex justify-between py-3 border-y-2 border-[#066b3a]">
              <span className="text-gray-800 font-bold text-lg">Total:</span>
              <span className="text-gray-800 font-bold text-lg">
                {invoice.total.toLocaleString()} TZS
              </span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center text-gray-600 border-t-2 border-[#066b3a] pt-8">
          <p className="font-semibold text-gray-800 mb-2">Thank you for your business!</p>
          <div className="space-y-1">
            <p>For any queries, please contact us at info@spade.co.tz</p>
            <p>Or call us at: +255 (0)653461126/+255(0)754574743</p>
          </div>
        </div>
      </div>

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          @page {
            size: A4;
            margin: 1.5cm;
          }
          
          html, body {
            width: 210mm;
            height: 297mm;
            margin: 0;
            padding: 0;
          }

          body * {
            visibility: hidden;
          }

          .print\\:hidden {
            display: none !important;
          }

          .max-w-4xl {
            max-width: none !important;
            margin: 0 !important;
          }

          .bg-white,
          .bg-white * {
            visibility: visible;
            color-adjust: exact !important;
            -webkit-print-color-adjust: exact !important;
          }

          .p-8 {
            padding: 0 !important;
          }
        }
      `}</style>
    </div>
  );
} 